name = "hono-mongo-cloudflare-worker-boilerplate"
compatibility_date = "2024-02-29"
compatibility_flags = ["nodejs_compat"]

[vars]
REALM_APP_ID="REALM_APP_ID"
REALM_API_KEY="REALM_API_KEY"
CRYPTO_KEY="CRYPTO_KEY"